### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by javierfernandezfidalgo** [neuralhydrology/neuralhydrology#100]
Hello everyone,

I'm trying to set up the CAMELS US catchment attributes section of the prerequisites notebook but I cannot find the camels_attributes_v2.0.zip file that is needed for the finetuning tutorial.

It seems that the links to the database files provided in the documentation are a bit obsolete now. Could it be possible to update that section and provide a working link to that file?

Thanks in advance.

Javier

**Comment by kratzert** [comment]
Thanks, it seems indeed like NCAR moved the files to a different location. All files, including the attributes can be downloaded from [https://gdex.ucar.edu/dataset/camels.html](https://gdex.ucar.edu/dataset/camels.html). You can also click on "Individual files" and only select the attribute .txt files (make sure to place them in the correct folder as described in the data prerequisite tutorial).

I will open an issue for us internally do fix the tutorials to account for the change. Thanks for letting us know.

**Comment by javierfernandezfidalgo** [comment]
Thank you very much for your advice, I got all the tutorial examples up and running. 
Keep up the good work!
