### ISSUE TITLE
Latest version of `matplotlib` compatibility

### ISSUE THREAD

**Issue by smaebius** [neuralhydrology/neuralhydrology#109]
Hello! While using the latest version of `matplotlib` (v3.7.1), I run into the following error when importing `from neuralhydrology.evaluation import metrics`:

```AttributeError: module 'matplotlib.axes' has no attribute '_subplots'```

This was solved by downgrading `matplotlib` to v3.6.3. Thanks!

**Comment by kratzert** [comment]
Thanks, yes, I recently identified the same issue but haven't pushed a fix yes. Be aware that there might also be a problem with the most recent torch version and our environment file. I am trying to get this solved in the next days, but thanks for reporting.

**Comment by kratzert** [comment]
Fixed in #110, please upgrade to the newest version and let us know if you encounter any other problem.
