### ISSUE TITLE
One missing subdirectory in CAMELS US dataset

### ISSUE THREAD

**Issue by Kavindra95** [neuralhydrology/neuralhydrology#117]
There is no "camels_attributes_v2.0" subdirectory in "basin_dataset_public_v1p2" folder which was downloaded from https://gdex.ucar.edu/dataset/camels/file/basin_timeseries_v1p2_metForcing_obsFlow.zip

**Comment by gauchm** [comment]
These attributes need to be downloaded separately, see here: https://neuralhydrology.readthedocs.io/en/latest/tutorials/data-prerequisites.html#CAMELS-US-catchment-attributes
