### ISSUE TITLE
Forcings are mandatory in config

### ISSUE THREAD

**Issue by jmframe** [neuralhydrology/neuralhydrology#12]
Hi Freddy,

I see that defining forcing product/s is now mandatory in the configuration file. I was previously bringing in new forcing data through _load_basin_data, but I assume that is bad practice, and that I should define a new forcing product. Does that sound correct?

Thanks
Jonathan

**Comment by kratzert** [comment]
Hi Jonathan,
`forcings` is only a mandatory config argument if you set `dataset` to either `camels_us` or `hourly_camels_us`. This is the only places, where `cfg.forcings` is queried from the `Config` object.

Your approach sounds right to me (but it is the same as previously): If you have multiple forcing products for one data set, then you actually load this data in the `_load_basin_data` method of that dataset class. You can look at https://github.com/neuralhydrology/neuralhydrology/blob/ab1d7a4560ee4d0035668c352d8bc8fdd75ebfd7/neuralhydrology/datasetzoo/camelsus.py#L72 for an example how to load different (and/or multiple) forcing products within a single dataset.

You should then be able to use/add you new forcing product in the `forcings` argument in the config file and you class will know what to do. Just make sure that a) your  `_load_basin_data` method does return a single dataframe with potentially all forcing products combined and b) to find a strategy for how to deal with variable names when using multiple forcing products. E.g. for the CAMELS US data set we append the forcing product to the variable name in case of multiple forcing products, which then has to be accounted for in the list of `dynamic_inputs`.

Does that solve your question?

**Comment by jmframe** [comment]
Yes that does. Thank you!

**Comment by kratzert** [comment]
Great! I'll close this issue then. Feel free to re-open if you have a follow-up question or open another issue if you have any other question.
