### ISSUE TITLE
[BUG] 8_basins_test_set.txt 

### ISSUE THREAD

**Issue by Friso1987** [neuralhydrology/neuralhydrology#122]
**Describe the bug**
The config.yml file specifies the required files for training, testing, and validation. However, the tutorial does not provide examples of how these files should be formatted or what information they should contain.

**To Reproduce**
To reproduce the issue, follow these steps:

Go through the tutorial.
Run the command 'nh-run train --config-file /path/to/config.yml'.
Encounter the following error: FileNotFoundError: [Errno 2] No such file or directory: 'data\8_basins_dev_set.txt'.

**Description of the dataset**
I use the out-of-the-box CAMELS dataset. As stated in the tutorial.

**Desktop & Environment (please complete the following information):**
 - OS: WINDOWS

**Comment by kratzert** [comment]
Hi @Friso1987, did you check the documentation? I would say it is quite clear how these files should look like. Check https://neuralhydrology.readthedocs.io/en/latest/usage/config.html for these config arguments where you find 

> Full or relative path to a text file containing the training basins (use data set basin id, one id per line).

You can also check the directories of the tutorials, e.g. https://github.com/neuralhydrology/neuralhydrology/tree/master/examples/06-Finetuning, where you find the 531 basin file used in this tutorial.
