### ISSUE TITLE
Error in FDC slope signatures formula?

### ISSUE THREAD

**Issue by raoulcollenteur** [neuralhydrology/neuralhydrology#125]
Hi all,

I was checking the computation for the slope of the FDC [see here](https://github.com/neuralhydrology/neuralhydrology/blame/b3ab73cfd58fd7bc765c0e0f584d79927e403dda/neuralhydrology/evaluation/signatures.py#LL602C3-L603C102]), because I am struggling with this for our implementation in Pastas. 
So first of all, thanks for sharing code and not numbers so people can try and check things! I noted that one of the round brackets might be misplaced:

`value = (np.log(fdc[idx_lower].values + 1e-8)) - np.log(fdc[idx_upper].values + 1e-8) / (upper_quantile - lower_quantile)`

should be:

`value = (np.log(fdc[idx_lower].values + 1e-8) - np.log(fdc[idx_upper].values + 1e-8)) / (upper_quantile - lower_quantile)`

I think?

Can do a PR if I am correct and if that is helpful :)

Cheers,
Raoul

**Comment by gauchm** [comment]
Good catch, thanks for flagging this! You're welcome to open a PR, otherwise we'll fix it ourselves with the next release.

**Comment by kratzert** [comment]
Thanks, indeed a good find. Let us know in case you plan to open a PR, so we won't do it ourselves :)

**Comment by gauchm** [comment]
Fixed with #129
