### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by Kavindra95** [neuralhydrology/neuralhydrology#141]
Recently, I started to learn about nueralhydrology and have little knowledge of python. When I try to run your tutorials, the " test " folder required for evaluation is not created in "test_run" folder. What can be the issue? Thank you.

**Comment by kratzert** [comment]
Can you be a bit more specific. The "test" subdirectory is not _required_ for evaluation but instead is created in the process of evaluating the model on the test set. Therefore I struggle to understand your problem. Can you maybe specify which tutorial you are trying to run and copy the error message (or make a screenshot)

**Comment by Kavindra95** [comment]
I am sorry, I found there was a mistake from my side. Now I can run "Introduction to NeuralHydrology" tutorial. And again I am facing a problem when I try to change training, validating and testing periods. I do not get simulated results after year 2008. I attach two screenshots below. Thank you.

![Periods](https://github.com/neuralhydrology/neuralhydrology/assets/133155843/aa78d3fd-e36f-4830-9958-e4bff01ff1db)
![Plot](https://github.com/neuralhydrology/neuralhydrology/assets/133155843/724e94dc-efa0-4f40-a5bd-c9b39a1b0b3b)

**Comment by Kavindra95** [comment]
Dear Dr. Kratzert,

Thank you for getting back to me. As you mentioned, the problem was the
unavailability of forcing input data after 2008. I could get the results
successfully after adjusting the 3 periods accordingly. (The tutorial I
followed was "Introduction to NeuralHydrology" tutorial which used the
"CAMELS_US" data set)

How can I adjust the configuration file to get a sequence of predictions? I
changed the "model" to "sequential_forecast_lstm" and added
"forecast_seq_length" key to the configuration file and ran the model, but
a few errors were encountered. I am not sure that the changes I made were
correct. I look forward to hearing from you. Thank you for your time.

Best regards,
Kavindra.

**Comment by danklotz** [comment]
> How can I adjust the configuration file to get a sequence of predictions?

You are probably seeking for the `predict_last_n` config argument (see [here](https://neuralhydrology.readthedocs.io/en/latest/usage/config.html))

**Comment by Kavindra95** [comment]
Thanks, I'll check it out.

**Comment by Kavindra95** [comment]
Good day,

Hope this email finds you well. I just look for a clue again. Is there any
way to change the "last n value" of the sequences at each time step? (as an
example if I want to change the last 3 values of input sequences to zero,
at each time step)

Thank you,
Kavindra.

**Comment by Kavindra95** [comment]
Hello,

I just wanted to check if you got any chance to look at my previous email.

Thank you,
Kavindra

**Comment by gauchm** [comment]
I don't think we support this out of the box. But you can easily adapt the `__getitem__` method in basedataset.py to set the last n values of the features in `x_d` (or `x_h`/`x_f` for forecasting models) to zero, which should do exactly what (I think) you describe.

**Comment by Kavindra95** [comment]
Thank you for the hint. Before replacing last n values by whatever value,
do I have to normalize it?

Kavindra.

**Comment by gauchm** [comment]
Whatever you do in getitem is happening after normalization, so if you set some value to x there, it will arrive as x in the model. So if you use 0 like in your example, the model would think that the last n time steps of that variable are as high as the variable's mean (if you use zero-mean/unit variance normalization).

**Comment by Kavindra95** [comment]
Ok, thanks for the clarification.

**Comment by Kavindra95** [comment]
Hi Mr. Martin,

Your previous information helped a lot. Now I just want to clarify how
"lagged_features" works. I just have 2 basic questions mentioned below.

1. if I add one of the "dynamic_inputs" input variables as a
"lagged_features", does the model ignore the original/raw feature of the
lagged feature as an input?
2. if I use 1 number of lagged time steps, does the model consider the
previous time step value of the original data as the current time step
value of the lagged data?

I attached a screenshot of my configuration file showing how I added the
"lagged_features". I am just wondering it is the right way or not.

Thank you,
Kavindra.

**Comment by gauchm** [comment]
Re 1: The model will use all the variables you specify in dynamic_inputs. If you specify the original feature there, it will be used. If you only specify the lagged feature, it won't.
Re 2: I think the answer to your question is yes, but I'm not sure I understand the question. We use [pandas shift](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shift.html#pandas-dataframe-shift), so the effect is the same as it is there.

Maybe you just fire up a juypter notebook or a colab and inspect the data returned by your dataset given your config? Maybe do some plots of the different timeseries that the dataset returns? You can find an example for loading a dataset in [this tutorial](https://neuralhydrology.readthedocs.io/en/latest/tutorials/inspect-lstm.html) (especially cell 7). This way, you'll get a better understanding of the effects of your config settings.

**Comment by Kavindra95** [comment]
Ok, thanks for the clarification.
