### ISSUE TITLE
[BUG] validation fails if saving all output without saving validation results

### ISSUE THREAD

**Issue by shamshaw** [neuralhydrology/neuralhydrology#158]
Came across a minor bug from a probably uncommon configuration that causes validation to fail. If a configuration is run with metrics calculated and `save_all_output` set to True, but without `save_validation_results` set to True, then the validation fails due to not being able to find results when saving metrics.

In Tester, I think just adding in `and results is not None` in the metrics saving condition does the trick to fix. 
```
    # save metrics any time this function is called, as long they exist
    if self.cfg.metrics and results is not None:
        df = metrics_to_dataframe(results, self.cfg.metrics)
        metrics_file = parent_directory / f"{self.period}_metrics.csv"
        df.to_csv(metrics_file)
        LOGGER.info(f"Stored metrics at {metrics_file}")
```

**Comment by kratzert** [comment]
Thanks, I will make sure that this finds its way into the next release, or else, you could also just submit this snippet as a PR :)
