### ISSUE TITLE
[REQUEST] Documentation-paper "Global prediction of extreme floods in ungauged watersheds"

### ISSUE THREAD

**Issue by jamesYu365** [neuralhydrology/neuralhydrology#192]
Hello, Kratzert, 

I recently read your paper, "Global prediction of extreme floods in ungauged watersheds," and I found it really impressive. I'm very interested in the LSTM model you developed and its training process.

In the Code Availability section of your paper, you mentioned that the forecasting model and other AI streamflow forecasting models were integrated into the NeuralHydrology code base at https://neuralhydrology.github.io/. However, I couldn't find the specific model or the related documentation in the repo.

Could you please point me to where I can find the code for the LSTM model used in your paper? Additionally, if it's possible, could you share the training and evaluation code? It would be really helpful for my research.

Thanks a lot for your time and help!

**Comment by gauchm** [comment]
There are a number of "forecast" model implementations in neuralhydrology. The one you are probably looking for is this model: https://neuralhydrology.readthedocs.io/en/latest/usage/models.html#handoff-forecast-lstm
