### ISSUE TITLE
Loss NaN during training

### ISSUE THREAD

**Issue by SebaDro** [neuralhydrology/neuralhydrology#33]
Hi guys,

by training on the CAMELS-GB dataset I ran into an issue that similary has been mentioned in #8. After some epoches, loss is calculated as NaN and training stops with an error:
```
Uncaught exception
Traceback (most recent call last):
  File "/opt/conda/bin/nh-run", line 33, in <module>
    sys.exit(load_entry_point('neuralhydrology', 'console_scripts', 'nh-run')())
  File "/home/Sebastian/projects/neuralhydrology/neuralhydrology/nh_run.py", li e 43, in _main
    start_run(config_file=Path(args["config_file"]), gpu=args["gpu"])
  File "/home/Sebastian/projects/neuralhydrology/neuralhydrology/nh_run.py", line 76, in start_run
    start_training(config)
  File "/home/Sebastian/projects/neuralhydrology/neuralhydrology/training/train.py", line 22, in start_training
    trainer.train_and_validate()
  File "/home/Sebastian/projects/neuralhydrology/neuralhydrology/training/basetrainer.py", line 206, in train_and_validate
    self._train_epoch(epoch=epoch)
  File "/home/Sebastian/projects/neuralhydrology/neuralhydrology/training/basetrainer.py", line 295, in _train_epoch
    raise RuntimeError(f"Loss was NaN for {nan_count} times in a row. Stopped training.")
RuntimeError: Loss was NaN for 1 times in a row. Stopped training.
```
I used [this config file](https://gist.github.com/SebaDro/3dec8700f00eec7710fbe46e60cc87e3) and [this basin list](https://gist.github.com/SebaDro/2e92af7b8e753cf0343d319398c240f6) for training.

I know, some of the basins have no complete discharge timeseries for the specified training period (01/01/1981 - 31/12/2010) since single rows have NaN values for `discharge_spec`. According to #8, I assumed that single NaN values will be filtered for calculating loss.

Do I have to ensure, that no NaN values are present within the dynamic inputs by specifying different training periods per basin? 

Maybe, @tommylees112 has some helpful hints since he has already trained some models on the CAMELS-GB?

Thanks!

**Comment by kratzert** [comment]
Hi @SebaDro,

the NaNs in `discharge_spec` of the training period should not be the problem, since those samples are excluded from the loss computation. We also check for NaNs in the dynamic and static inputs.
Also, the fact that this happened only after a few epochs (i.e. all samples have been used multiple times) means that this should not be a data issue. Otherwise it would have happened the first time you see that particular sample. I know that @tommylees112 did use our library for his current CAMELS GB paper, so I would assume that it works generally. 

After how many epochs does this happen? Can you maybe send the tensorboard logfile and paste the content of `output.log`.

**Comment by SebaDro** [comment]
Thanks @kratzert for replying.

>Also, the fact that this happened only after a few epochs (i.e. all samples have been used multiple times) means that this should not be a data issue. Otherwise it would have happened the first time you see that particular sample.

Absolutely, I had the same thoughts and wondered about the stop after a few succesfully finished epoches.

> After how many epochs does this happen?

For different runs, the error raised differently. Sometimes during 3. epoche and another time after 6. epoche.

Here is the [output.log](https://gist.github.com/SebaDro/a4c861cf9cef00257869a138b286c00d). I also uploaded the whole [training folder](https://hs-bochum.sciebo.de/s/09pgbfx8J2Wdovo), hoping this would be helpful.

I trained on a GCP VM with the setup listed below:
* 8 vCPUs
* 52 GB memory
*  NVIDIA Tesla T4 GPU
* PyTorch:1.7
* CUDA 11.0

Many thanks again!

**Comment by SebaDro** [comment]
Oh wow, that's great. Lowering the three learning rates by factor 10 seems to did the trick. Up to now, no failure after 10 epoches of training. I'll give you a final feedback if training has been succesfull over the complete number of epoches.

**Comment by SebaDro** [comment]
As @kratzert mentioned in https://github.com/neuralhydrology/neuralhydrology/issues/33#issuecomment-811126457, loss increased very fast after a few epochs due to the amount of data in CAMELS-GB and the high learning rate. A small adjustment to the learning rates could fix the problem. Below you will find the configuration that worked for me:
```
epochs: 30
learning_rate:
    0: 1e-3
    20: 5e-4
    25: 1e-4
```
Feel free to close this issue since it has been solved.

Many thanks again!

**Comment by kratzert** [comment]
Happy that did do the trick
