### ISSUE TITLE
Which version of pytorch is requried for neuralhydrology?

### ISSUE THREAD

**Issue by rtaormina** [neuralhydrology/neuralhydrology#36]
Hey there,

Can you please telle me which version of PyTorch does NeuralHydrology works best with?

Thanks.

Cheers,
Riccardo

**Comment by kratzert** [comment]
Hi @rtaormina,
sorry for the late reply. I am not sure, what is the lowest version of PyTorch that works. Until recently I used v1.6 and last week I updated to v1.8. Both work fine.

We provide some conda environment files in the `environments` folder. If you install a Anaconda environment from one of those, you get the most recent version of PyTorch, which should work fine.

Best,
Freddy

**Comment by gauchm** [comment]
Just to fill the gap, although it's probably clear -- v1.7 also works fine from my experience. Unfortunately, I can't say anything about earlier PyTorch versions, either.

**Comment by rtaormina** [comment]
Thanks, much appreciated. 

I will let you know in case we end up using different versions and neuralhydrology still works.

Very best,
Riccardo
