### ISSUE TITLE
Problem executing example 4 for MTS-LSTM

### ISSUE THREAD

**Issue by subhashis** [neuralhydrology/neuralhydrology#67]
I tried to follow example 04 for MTS-LSTM with the provided instruction. Ran into file loading issue
    219         file_path = file_path[0]
    220     else:
--> 221         raise FileNotFoundError(f'No file for Basin {basin} at {discharge_path}')
    222 
    223     return pd.read_csv(file_path, index_col=['date'], parse_dates=['date'])

FileNotFoundError: No file for Basin 01022500 at /../data_neuralhydrology/CAMELS_US/hourly/usgs_streamflow

My data directory under CAMELS_US is 
/basin_mean_forcing
/hourly
/usgs_streamflow

I think its looking for basin file  "01022500_streamflow_qc.txt" in "usgs_streamflow" which is not there once I extract it from "usgs_streamflow_csv.tar.gz" 

Also how to use the associated .nc file with this example. Any help will be great. Thanks!

**Comment by gauchm** [comment]
Hi @subhashis,
You have found a small discrepancy between the data on zenodo and the way it is expected by the code:
In Zenodo, the discharge folder is called `usgs-streamflow`, while the code expects `usgs_streamflow` (minus vs. underscore).
We'll push a small fix to NeuralHydrology in the next release so that both folder names are recognized.

In the meantime, you can (a) simply rename the folder to `usgs_streamflow`, or (b) use the netCDF file, which will have the additional benefit to be faster.

To use the netCDF file, you need to download the .nc version from Zenodo (https://zenodo.org/record/4072701, usgs-streamflow-nldas_hourly.nc) and place it in the `hourly/` folder. NeuralHydrology will detect the file and automatically prefer it over loading the data from csv files, since this will be a lot faster.

**Comment by subhashis** [comment]
Thank you @gauchm ! That was helpful.

One other thing i observed with example 04 is that the config file mentions 'daymet' variables and files, but daymet data was not there in the example data. So I commented it out in the .yml file.

**Comment by gauchm** [comment]
The daymet data used in the tutorial are part of the default CAMELS dataset (they are at a daily resolution).
So if you have downloaded the basic CAMELS dataset as described in the [Quickstart](https://neuralhydrology.readthedocs.io/en/latest/usage/quickstart.html#data) section, you already have the daymet data in the folder `basin_mean_forcing/daymet`.

**Comment by Smile-L-up** [comment]
Hi @gauchm ,
I prepared the data according to the tutorial [https://neuralhydrology.readthedocs.io/en/latest/tutorials/data-prerequisites.html](https://neuralhydrology.readthedocs.io/en/latest/tutorials/data-prerequisites.html) and tried to follow example 04 for MTS-LSTM with the provided instruction. But the following error occurs：

```python
Traceback (most recent call last):
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\datasetzoo\basedataset.py", line 353, in _load_or_create_xarray_dataset
    df = df[keep_cols]
  File "D:\Smile_L\miniconda\envs\neuralhydrology\lib\site-packages\pandas\core\frame.py", line 4096, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "D:\Smile_L\miniconda\envs\neuralhydrology\lib\site-packages\pandas\core\indexes\base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "D:\Smile_L\miniconda\envs\neuralhydrology\lib\site-packages\pandas\core\indexes\base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['qobs_mm_per_hour'] not in index"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Smile_L\pycharm_files\neuralhydrology\examples\04-Multi-Timescale\multi-timescale.py", line 18, in <module>
    start_run(config_file=Path("1_basin.yml"))
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\nh_run.py", line 76, in start_run
    start_training(config)
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\training\train.py", line 19, in start_training
    trainer.initialize_training()
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\training\basetrainer.py", line 147, in initialize_training
    ds = self._get_dataset()
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\training\basetrainer.py", line 80, in _get_dataset
    return get_dataset(cfg=self.cfg, period="train", is_train=True, scaler=self._scaler)
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\datasetzoo\__init__.py", line 83, in get_dataset
    ds = Dataset(cfg=cfg,
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\datasetzoo\hourlycamelsus.py", line 57, in __init__
    super(HourlyCamelsUS, self).__init__(cfg=cfg,
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\datasetzoo\camelsus.py", line 60, in __init__
    super(CamelsUS, self).__init__(cfg=cfg,
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\datasetzoo\basedataset.py", line 146, in __init__
    self._load_data()
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\datasetzoo\basedataset.py", line 720, in _load_data
    xr = self._load_or_create_xarray_dataset()
  File "D:\Smile_L\pycharm_files\neuralhydrology\neuralhydrology\datasetzoo\basedataset.py", line 360, in _load_or_create_xarray_dataset
    raise KeyError("".join(msg))
KeyError: "The following features are not available in the data: ['qobs_mm_per_hour']. These are the available features: ['convective_fraction_nldas_hourly', 'longwave_radiation_nldas_hourly', 'potential_energy_nldas_hourly', 'potential_evaporation_nldas_hourly', 'pressure_nldas_hourly', 'shortwave_radiation_nldas_hourly', 'specific_humidity_nldas_hourly', 'temperature_nldas_hourly', 'total_precipitation_nldas_hourly', 'wind_u_nldas_hourly', 'wind_v_nldas_hourly', 'QObs(mm/h)', 'QObs count', 'qualifiers_nldas_hourly', 'utcoffset(h)_nldas_hourly', '(iv-camels)/camels_nldas_hourly', 'QObs_CAMELS(mm/h)', 'Year_daymet', 'Mnth_daymet', 'Day_daymet', 'Hr_daymet', 'dayl(s)_daymet', 'prcp(mm/day)_daymet', 'srad(W/m2)_daymet', 'swe(mm)_daymet', 'tmax(C)_daymet', 'tmin(C)_daymet', 'vp(Pa)_daymet']"

```

**Comment by gauchm** [comment]
@Smile-L-up I think you might be loading the data from the CSV file instead of the netcdf provided at https://zenodo.org/records/4072701. Apparently in the csv, the column is called QObs(mm/h), so you'd have to change that in the config. 
But the real recommendation would be to download the netcdf (usgs-streamflow-nldas_hourly.nc) because loading is a lot faster with that one.

**Comment by Smile-L-up** [comment]
thank you for your reply。After I changed qobs_mm_per_hour to QObs(mm/h) in the configuration file, it can run. But I don’t know if the following parameters need to be changed. These parameters have suffixes, which are different from the column names in the csv.

```python

forcings:
  - nldas_hourly
  - daymet

dynamic_inputs:
  1D:
    - prcp(mm/day)_daymet
    - srad(W/m2)_daymet
    - tmax(C)_daymet
    - tmin(C)_daymet
    - vp(Pa)_daymet
  1H:
    - convective_fraction_nldas_hourly
    - longwave_radiation_nldas_hourly
    - potential_energy_nldas_hourly
    - potential_evaporation_nldas_hourly
    - pressure_nldas_hourly
    - shortwave_radiation_nldas_hourly
    - specific_humidity_nldas_hourly
    - temperature_nldas_hourly
    - total_precipitation_nldas_hourly
    - wind_u_nldas_hourly
    - wind_v_nldas_hourly
    - prcp(mm/day)_daymet
    - srad(W/m2)_daymet
    - tmax(C)_daymet
    - tmin(C)_daymet
    - vp(Pa)_daymet
 ```

**Comment by gauchm** [comment]
The suffixes that describe the forcing product are fine and needed. See [here](https://neuralhydrology.readthedocs.io/en/latest/usage/config.html#data-settings) under `dynamic_inputs`.

**Comment by Smile-L-up** [comment]
Thank you for your reply!  
I tried to run the LSTM encoder decoder model (handoff_forecast_lstm) proposed by Google. I just changed the model parameter in the config to handoff_forecast_lstm, but the following error was prompted.
```python
ValueError: Model handoff_forecast_lstm does not support multiple frequencies.
```
Can you provide a running example? Any help will be great. Thanks!

**Comment by gauchm** [comment]
As the error states, the handoff LSTM does not support multi-frequency training. So you'll have to decide for either daily or hourly modeling, and only use inputs at the frequency you decide for. For daily modeling, the [finetuning config](https://github.com/neuralhydrology/neuralhydrology/blob/master/examples/06-Finetuning/531_basins.yml) might be a good start - you'd have to change the model name and add the model-specific parameters (see [here](https://neuralhydrology.readthedocs.io/en/latest/usage/config.html#handoff-forecast-model-settings)). For hourly modeling, you could use the same config, just replace the daily forcings/features with hourly ones (e.g., nldas_hourly) and adjust the sequence length. To be clear, this will likely not be a "good" config in the sense of giving you the best possible results, but it should get you to something that works and that you can build on.
